# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2274538c7776404900c3d3ecbb22602b"
name = "Biju & Cia. Connector"
handle = "biju-cia-connector"
application_url = "https://innovative-appliances-cio-mh.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://innovative-appliances-cio-mh.trycloudflare.com/auth/callback", "https://innovative-appliances-cio-mh.trycloudflare.com/auth/shopify/callback", "https://innovative-appliances-cio-mh.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
